version: '3'
services:
  my-name:
    build:
      context: ./
      dockerfile: dockerfile.dev

    ports:
      - "3000:3000"
    volumes:
      - .:/app
  tests:
    build:
      context: ./
      dockerfile: dockerfile.dev
    volumes:
      - .:/app
    command: ["npm" ,"run","test"]

  production:
    build:
      context: ./
      dockerfile: dockerfile

    volumes:
      - .:/app
